chore: enhancing zshrc setup

diff --git a/zshrc-template b/zshrc-template
--- a/zshrc-template
+++ b/zshrc-template
@@ -1,13 +1,36 @@
 #!/usr/bin/env zsh
 
+# Performance profiling (uncomment to debug slow startup)
+# zmodload zsh/zprof
+
 #
-# Exports
+# Environment Variables
 #
 export KEYTIMEOUT=1
 export ZSH_TMUX_FIXTERM=true
 export WORKSPACE_DIR=~/workspace
+
+# Locale
+export LANG=en_GB.UTF-8
+export LC_ALL=en_GB.UTF-8
+
+# Editor
+export EDITOR=vim
+export VISUAL="$EDITOR"
+
+# Pager
+export LESS='-R -M -i -j5'
+export PAGER='less'
+
+# Homebrew
+export HOMEBREW_NO_AUTO_UPDATE=1
+
 # Fix GPG https://github.com/keybase/keybase-issues/issues/2798
 export GPG_TTY=$(tty)
+
+#
+# Functions
+#
 
 # Function to add directories to PATH if they exist and are not already in PATH
 pathadd() {
@@ -16,6 +39,48 @@ pathadd() {
   fi
 }
 
+# Create directory and cd into it
+mkcd() {
+  mkdir -p "$1" && cd "$1"
+}
+
+# Extract any archive
+extract() {
+  if [ -f "$1" ]; then
+    case "$1" in
+      *.tar.bz2)   tar xjf "$1"    ;;
+      *.tar.gz)    tar xzf "$1"    ;;
+      *.bz2)       bunzip2 "$1"    ;;
+      *.rar)       unrar x "$1"    ;;
+      *.gz)        gunzip "$1"     ;;
+      *.tar)       tar xf "$1"     ;;
+      *.tbz2)      tar xjf "$1"    ;;
+      *.tgz)       tar xzf "$1"    ;;
+      *.zip)       unzip "$1"      ;;
+      *.Z)         uncompress "$1" ;;
+      *.7z)        7z x "$1"       ;;
+      *)           echo "'$1' cannot be extracted" ;;
+    esac
+  else
+    echo "'$1' is not a valid file"
+  fi
+}
+
+# Show listening ports
+ports() {
+  lsof -iTCP -sTCP:LISTEN -n -P
+}
+
+# Show external IP
+myip() {
+  curl -s https://api.ipify.org
+  echo
+}
+
+#
+# PATH Setup
+#
+
 # Homebrew
 if command -v brew &>/dev/null; then
   eval "$(/opt/homebrew/bin/brew shellenv)"
@@ -23,50 +88,152 @@ else
   echo "Homebrew not found. Please install Homebrew."
 fi
 
-# Set up NPM global path
 pathadd "/usr/local/share/npm/bin"
-
-# NVM setup
-export NVM_DIR="$HOME/.nvm"
-[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
-[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
-
-autoload -U add-zsh-hook
-load-nvmrc() {
-  local node_version="$(nvm version)"
-  local nvmrc_path="$(nvm_find_nvmrc)"
-
-  if [ -n "$nvmrc_path" ]; then
-    nvm use
-  elif [ "$node_version" != "system" ]; then
-    nvm use default
-  fi
-}
-add-zsh-hook chpwd load-nvmrc
-load-nvmrc
-
-# Add other directories to PATH
 pathadd "$HOME/Library/pnpm"
 pathadd "/opt/homebrew/bin"
 pathadd "/opt/homebrew/sbin"
 pathadd "$HOME/.bin"
-pathadd "$HOME/.cargo/bin"  # Rust binaries
+pathadd "$HOME/.cargo/bin"
 pathadd "/usr/local/bin"
 pathadd "/usr/bin"
 pathadd "/bin"
 pathadd "/usr/sbin"
 pathadd "/sbin"
 
-# Vi mode
+#
+# Lazy Load NVM (faster startup)
+#
+
+export NVM_DIR="$HOME/.nvm"
+
+# Lazy load nvm - only load when node/npm/nvm is called
+nvm() {
+  unset -f nvm node npm npx
+  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
+  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"
+  nvm "$@"
+}
+
+node() {
+  unset -f nvm node npm npx
+  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
+  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"
+  node "$@"
+}
+
+npm() {
+  unset -f nvm node npm npx
+  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
+  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"
+  npm "$@"
+}
+
+npx() {
+  unset -f nvm node npm npx
+  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
+  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"
+  npx "$@"
+}
+
+# Auto-load nvmrc on directory change (but only after nvm is loaded)
+autoload -U add-zsh-hook
+load-nvmrc() {
+  if command -v nvm_find_nvmrc &>/dev/null; then
+    local node_version="$(nvm version)"
+    local nvmrc_path="$(nvm_find_nvmrc)"
+
+    if [ -n "$nvmrc_path" ]; then
+      nvm use
+    elif [ "$node_version" != "system" ]; then
+      nvm use default
+    fi
+  fi
+}
+add-zsh-hook chpwd load-nvmrc
+
+#
+# Zsh Options
+#
+
+# History
+HISTFILE=~/.zsh_history
+HISTSIZE=10000
+SAVEHIST=10000
+setopt EXTENDED_HISTORY          # Write timestamp to history
+setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicates first
+setopt HIST_IGNORE_DUPS          # Don't record duplicates
+setopt HIST_IGNORE_SPACE         # Don't record commands starting with space
+setopt HIST_VERIFY               # Show command with history expansion before running
+setopt SHARE_HISTORY             # Share history between sessions
+
+# Directory navigation
+setopt AUTO_CD                   # cd by typing directory name
+setopt AUTO_PUSHD                # Push directories onto stack
+setopt PUSHD_IGNORE_DUPS        # Don't push duplicates
+setopt PUSHD_MINUS              # Swap meaning of +/-
+
+# Completion
+setopt ALWAYS_TO_END            # Move cursor to end after completion
+setopt AUTO_MENU                # Show completion menu on tab
+setopt COMPLETE_IN_WORD         # Complete from both ends of word
+
+#
+# Vi Mode with Enhancements
+#
+
 bindkey -v
 
-# Theme
-eval "$(oh-my-posh init zsh --config $(brew --prefix oh-my-posh)/themes/catppuccin.omp.json)"
-source ~/workspace/catppuccin_mocha-zsh-syntax-highlighting.zsh
+# Fix backspace in vi mode
+bindkey -v '^?' backward-delete-char
+
+# Better vi mode bindings
+bindkey '^R' history-incremental-search-backward
+bindkey '^P' up-history
+bindkey '^N' down-history
+
+# jk to exit insert mode
+bindkey -M viins 'jk' vi-cmd-mode
+
+# Edit command in editor with 'v' in normal mode
+autoload -Uz edit-command-line
+zle -N edit-command-line
+bindkey -M vicmd 'v' edit-command-line
+
+# Change cursor shape based on vi mode
+function zle-keymap-select {
+  if [[ ${KEYMAP} == vicmd ]] || [[ $1 = 'block' ]]; then
+    echo -ne '\e[1 q'  # Block cursor
+  elif [[ ${KEYMAP} == main ]] || [[ ${KEYMAP} == viins ]] || [[ ${KEYMAP} = '' ]] || [[ $1 = 'beam' ]]; then
+    echo -ne '\e[5 q'  # Beam cursor
+  fi
+}
+zle -N zle-keymap-select
+
+# Start with beam cursor
+echo -ne '\e[5 q'
+
+# Reset cursor on each prompt
+function zle-line-init {
+  echo -ne '\e[5 q'
+}
+zle -N zle-line-init
 
 #
-# Antigen config
+# Colored Man Pages
 #
+
+export LESS_TERMCAP_mb=$'\e[1;32m'
+export LESS_TERMCAP_md=$'\e[1;32m'
+export LESS_TERMCAP_me=$'\e[0m'
+export LESS_TERMCAP_se=$'\e[0m'
+export LESS_TERMCAP_so=$'\e[01;33m'
+export LESS_TERMCAP_ue=$'\e[0m'
+export LESS_TERMCAP_us=$'\e[1;4;31m'
+
+#
+# Antigen Plugin Manager
+#
+
 source ~/.bin/antigen/antigen.zsh
 
 antigen use oh-my-zsh
@@ -80,22 +247,163 @@ antigen bundle aws
 antigen bundle zsh-users/zsh-completions
 antigen bundle zsh-users/zsh-autosuggestions
 antigen bundle zsh-users/zsh-syntax-highlighting
+antigen bundle zsh-users/zsh-history-substring-search
 
 antigen apply
 
 #
-# Shell completions
+# History Substring Search (bind after plugins load)
 #
 
-# GitHub CLI completion
+bindkey '^[[A' history-substring-search-up
+bindkey '^[[B' history-substring-search-down
+bindkey -M vicmd 'k' history-substring-search-up
+bindkey -M vicmd 'j' history-substring-search-down
+
+#
+# Completion Configuration
+#
+
+# Case-insensitive completion
+zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
+
+# Menu selection
+zstyle ':completion:*' menu select
+
+# Group results by category
+zstyle ':completion:*' group-name ''
+
+# Add colors to completion
+zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
+
+# Better descriptions
+zstyle ':completion:*:descriptions' format '%F{yellow}-- %d --%f'
+zstyle ':completion:*:warnings' format '%F{red}-- no matches found --%f'
+
+#
+# FZF Integration
+#
+
+if command -v fzf &>/dev/null; then
+  # Setup fzf key bindings and fuzzy completion
+  eval "$(fzf --zsh)"
+
+  # Use fd for faster file finding (if available)
+  if command -v fd &>/dev/null; then
+    export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
+    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
+  fi
+
+  # Catppuccin Mocha theme for fzf
+  export FZF_DEFAULT_OPTS=" \
+    --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
+    --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
+    --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"
+fi
+
+#
+# Zoxide (smart cd)
+#
+
+if command -v zoxide &>/dev/null; then
+  eval "$(zoxide init zsh)"
+fi
+
+#
+# Theme
+#
+
+eval "$(oh-my-posh init zsh --config $(brew --prefix oh-my-posh)/themes/catppuccin.omp.json)"
+source ~/workspace/catppuccin_mocha-zsh-syntax-highlighting.zsh
+
+#
+# Additional Completions
+#
+
+# GitHub CLI
 if command -v gh &>/dev/null; then
-    eval "$(gh completion -s zsh)"
+  eval "$(gh completion -s zsh)"
 fi
 
-# pnpm completion
+# pnpm
 if command -v pnpm &>/dev/null; then
-    [[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true
+  [[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true
 fi
 
-# Neofetch
+#
+# Aliases
+#
+
+# Directory listing
+alias ls='ls -G'
+alias ll='ls -lah'
+alias la='ls -A'
+alias l='ls -CF'
+
+# Directory navigation
+alias ..='cd ..'
+alias ...='cd ../..'
+alias ....='cd ../../..'
+alias -- -='cd -'
+alias d='dirs -v'  # Show directory stack
+
+# Git shortcuts
+alias gs='git status'
+alias ga='git add'
+alias gc='git commit'
+alias gp='git pull'
+alias gph='git push'
+alias gco='git checkout'
+alias gd='git diff'
+alias gl='git log --oneline --graph --decorate'
+alias gb='git branch'
+
+# Docker shortcuts
+alias d='docker'
+alias dc='docker-compose'
+alias dps='docker ps'
+alias dimg='docker images'
+
+# Kubernetes (if installed)
+if command -v kubectl &>/dev/null; then
+  alias k='kubectl'
+  alias kgp='kubectl get pods'
+  alias kgs='kubectl get services'
+  alias kgd='kubectl get deployments'
+fi
+
+# Terraform (if installed)
+if command -v terraform &>/dev/null; then
+  alias tf='terraform'
+  alias tfi='terraform init'
+  alias tfp='terraform plan'
+  alias tfa='terraform apply'
+fi
+
+# Python
+alias py='python3'
+alias pip='pip3'
+
+# Quick edit
+alias zshrc='$EDITOR ~/.zshrc'
+alias reload='source ~/.zshrc'
+
+#
+# Conditional Profile Loading
+#
+
+# Load work-specific config if it exists
+[[ -f ~/.zshrc.work ]] && source ~/.zshrc.work
+
+# Load local config if it exists
+[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
+
+#
+# Startup
+#
+
+# Show system info on new terminal
 neofetch
+
+# Performance profiling (uncomment to see results)
+# zprof
